# Version format
version: ({build})

# Build worker image (VM template)
image: Visual Studio 2019

# Fix CRLF
init:
- git config --global --unset core.autocrlf

# Scripts that run after cloning repository
install:
- ps: . .\Tests\AppVeyor.ps1 -Initialize
- ps: Install-Module -Name Pester -Force -SkipPublisherCheck
- ps: Install-Module -Name Assert -Force
## Install other PowerShell Core version (Optional)
- ps: '& .\Tests\InstallPowerShell.ps1 -Version "7.0.0-preview.1"'
- pwsh: Install-Module -Name Pester -Force
- pwsh: Install-Module -Name Assert -Force

# To disable automatic builds
build: off

# To run your custom scripts instead of automatic tests
test_script:
- ps: . .\Tests\AppVeyor.ps1
- pwsh: . .\Tests\AppVeyor.ps1

# Finalize pass - collect and upload results
- ps: . .\Tests\AppVeyor.ps1 -Finalize

# Skipping commits with particular message or from specific user
skip_commits:
  message: /\[Skip\]/

# Including commits with particular message or from specific user
#only_commits:
#  message: /\[build\]/                # Start a new build if message contains 'build'

environment:
  NugetApiKey:
    secure: K+vkseiHQEbiNnvY20ZSYA+Jl0fSAbfyWc1/454xA3FgZRIRUw5vDPG2eyFFc5lj

deploy_script:
- ps: $null = Install-PackageProvider -Name NuGet -Force ; . .\Tests\Deploy.ps1 -PowerShellGallery -AppVeyorZip