# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - '*'
    # - master
    # - releases/*
  paths:
    exclude:
    - '*.md'

pool:
  vmImage: 'windows-2019'

steps:
- powershell: 'Install-Module -Name Pester -Force -SkipPublisherCheck'
  displayName: 'Update Pester'
- powershell: './Tests/CI.ps1 -Test'
  displayName: 'Install and Test'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**/TestResults*.xml'
    failTaskOnFailedTests: true

- powershell: './Tests/CI.ps1 -Artifact'
  displayName: 'Set ModulePath for Artifact'
- powershell: Write-Host "Hello World from $Env:ModulePath." ; Get-ChildItem $Env:ModulePath #test
- task: CopyFiles@2
  inputs:
    contents: C:\Users\VssAdministrator\Documents\WindowsPowerShell\Modules\Module.Template\**
    targetFolder: $(Build.ArtifactStagingDirectory)
  displayName: 'Set $(ModulePath)*'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'